# Generated by Django 5.1.5 on 2025-03-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusnavigationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
