# Generated by Django 5.1.5 on 2025-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusnavigationapp', '0002_bookmark_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='level',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='end_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='start_level',
            field=models.IntegerField(default=0),
        ),
    ]
