# Generated by Django 5.1.5 on 2025-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusnavigationapp', '0003_remove_bookmark_level_bookmark_end_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='end_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='end_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='end_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='start_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='start_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
